Asterix/Asterix/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views


from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include # url
from blog.views import (
    blog_post_create_view,
)

from searches.views import search_view
from .views import (
    home_page,
    about_page,
    contact_page,
    example_page
)

urlpatterns = [
    path('', home_page),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),

    #xtra URLs
    path('blog-new/', blog_post_create_view),
    path('blog/', include('blog.urls')),
    path('search/', search_view),
    # re_path(r'^blog/(?P<slug>\w+)/$', blog_post_detail_view),
    path('page/', about_page),
    path('pages/', about_page),
    re_path(r'^pages?/$', about_page),
    re_path(r'^about/$', about_page),
    path('example/', example_page),
    path('contact/', contact_page),
]

if settings.DEBUG:
    # test mode
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Asterix/accounts/urls.py
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings

app_name = 'accounts'

urlpatterns = [
    path('', home),
    path('user/register/', register),
    path('auth/', auth),
    path('user/login/', login_view, name='login'),
    path('user/logout/', logout_view, name='logout'),
    path('^activate/(?P<code>[a-z0-9].*)/$', activate_user_view),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Asterix/blog/urls.py
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings

app_name = 'blog'

urlpatterns = [
    path('', blog_post_list_view),
    path('<str:slug>/', blog_post_detail_view),
    path('<str:slug>/edit/', blog_post_update_view),
    path('<str:slug>/delete/', blog_post_delete_view),
]

Asterix/templates/about.html
{% extends "base.html" %}

{% block head_title %}About Us{% endblock %}

{% block content %}
    <p>This is more about stuff {{ title }}</p>
{% endblock %}

Asterix/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block head_title %}{% endblock %} | Asterix</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class='container-fluid'>
         {% block content %}
            {% endblock %}
    </div>

    {% include 'js.html' %}
  </body>
</html>

Asterix/templates/form.html
{% extends "base.html" %}



{% block content %}

{% if title %}
    <h1>{{ title }}</h1>
{% endif %}

<form method='POST' action='.' enctype='multipart/form-data'> {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Send</button>
</form> 


{% endblock %}

Asterix/templates/hello_world.html
{% extends "base.html" %}

Asterix/templates/home - Copy.html
<!doctype html>
<html lang="en">
  <head>
  	{% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>{{ my_title }}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/cover/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'accounts/default/css/boot_css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'accounts/css/main/coverpage.css' %}" rel="stylesheet">
  </head>

  <body class="text-center" id="#home">

    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
      <header class="masthead mb-auto">
        <div class="inner">
          <h3 class="masthead-brand">Asterix</h3>
          <nav class="nav nav-masthead justify-content-center">
            <a class="nav-link active" href="#home">Home</a>
            <a class="nav-link active" href="#">Features</a>
            <a class="nav-link" href="#">Login</a>
            <a class="nav-link" href="#">Sign up</a>
            <a class="nav-link" href="#">Contact</a>
          </nav>
        </div>
      </header>

      <main role="main" class="inner cover">
        <h1 class="cover-heading">{{ title }}</h1>
        <p class="lead">

            <!-- Slideshow container -->
            <div class="slideshow-container">

              <!-- Full-width slides/quotes -->
              <div class="mySlides">
                <q>I've built this website to assist you all in your academic period though your stay in <strong>FUPRE</strong>.</q>
                <p class="author">- Scofield WhiteFire</p>
              </div>

              <div class="mySlides">
                <q>The wesite runs on a <strong>Django 2.2 </strong>version and bootstrap alone side <strong>Angular</strong> in accompanied with some javascript</q>
                <p class="author">- Scofield WhiteFire</p>
              </div>

              <div class="mySlides"><q>The design and stucture was done from strach with hand by <strong>darksnow</strong></q>
                <p class="author">- Scofield whiteFire</p>
              </div>

              <!-- Next/prev buttons -->
              <a class="preva" onclick="plusSlides(-1)">&#10094;</a>
              <a class="nexta" onclick="plusSlides(1)">&#10095;</a>
            </div>

            <!-- Dots/bullets/indicators -->
            <div class="dot-container">
              <span class="dot" onclick="currentSlide(1)"></span> 
              <span class="dot" onclick="currentSlide(2)"></span> 
              <span class="dot" onclick="currentSlide(3)"></span> 
            </div>
          </p>
      </main>

      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p>Asterix || Brought to you by <a class="footerlink" href="https://getbootstrap.com/">Maroon Ent. Group</a> , Design & Coded by <a class="footerlink" href="https://twitter.com/mdo">ScofieldTECH.INC</a>.</p>
        </div>
      </footer>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="{% static 'accounts/js/main/coverpage.js' %}"></script>
  </body>
</html>

Asterix/templates/home.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>{{ title }} || Asterix </title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/jumbotron/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'accounts/default/css/boot_css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'accounts/css/main/coverpage.css' %}" rel="stylesheet">
  </head>

  <body>

    <nav class="addToNav navbar navbar-expand-md navbar-dark fixed-top bg-light">
      <a class="rixTextLogo navbar-brand h3" style="color: black" href="#">Asterix</a>
      <button style="color: black" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        &nbsp &nbsp 
      <div class="collapse navbar-collapse" id="navbarsExampleDefault" >
        <ul class="navbar-nav mr-auto">
          <li class="nav-item ">
            <a class=" rixHover nav-link" href="#" style="color: black">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="rixHover nav-item">
            <a class="nav-link" href="#" style="color: black">Featues</a>
          </li>
          <li class="nav-item">
            <a class="rixHover nav-link" data-toggle="modal" data-target="#menuModel3" href="#" style="color: black">Contact</a>
          </li>
          <!--<li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something here</a>
            </div>
          </li> -->
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <h5><a href="{% url 'accounts:login' %}" class="addToLink">Login</a></h5>&nbsp &nbsp 
          <button class="rixBtn rixBtn-outline btn btn-outline-success my-2 my-sm-0" type="submit">Sign up</button>
      </div>
    </nav>

    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="rixInfoText display-3">Welcome!</h1>
          <p>Asterix brings you lots of package, it has been design to assist you with all your school activitest like your handout at a cheaper rate, New update, latest gist on and off campus, Entertainment and lots more . . .</p>
          <p><a class="btn btn-primary btn-lg" href="#" data-toggle="modal" data-target="#readMoreCover" role="button">Read more &raquo;</a></p>
        </div>
      </div>

      <div class="container">
        <!-- Example row of columns -->
        <div class="row">
          <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
          <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
          <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
        </div>

        <hr>

      </div> <!-- /container -->
      <!-- Button trigger modal -->

<!-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter" >
  Launch demo modal
</button> -->

<!-- Modal -->
<div class="modal fade" id="readMoreCover" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Welcome Note</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Asterix brings you lots of package, it has been design to assist you with all your school activitest like your handout at a cheaper rate, New update, latest gist on and off campus, Entertainment and lots more . . .
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>


<!-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Open modal for @mdo</button> -->

<div class="modal fade" id="menuModel3" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Contact Us</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Do wish to get in touch with us at <strong>Asterix</strong> feel free to leave a Comment below with your name and email with your message and we would get in touch with you within <i>2 working days</i> with a solution to your Comment...
        <hr>
        Telephone:&nbsp
        +234XXXXXXXX , +234XXXXXXXX , +234XXXXXXXX. <br>
        E-mail:&nbsp
        care@asterix.com
        <hr>
        You can also reach us on our social media handle
        <hr>
        <form>
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Your Name:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Your Email:</label>
            <input type="email" class="form-control" id="recipient-name">
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Message:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Send message</button>
      </div>
    </div>
  </div>
</div>
<!-- Copy
$('#exampleModal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Button that triggered the modal
  var recipient = button.data('whatever') // Extract info from data-* attributes
  // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
  // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
  var modal = $(this)
  modal.find('.modal-title').text('New message to ' + recipient)
  modal.find('.modal-body input').val(recipient)
}) -->

    </main>

    <footer class="container">
      <p>&copy; Asterix - 2019</p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="{% static 'accounts/js/main/vendor/jquery-slim.min.js' %}"><\/script>')</script>
    <script src="{% static 'accounts/js/main/vendor/popper.min.js' %}"></script>
    <script src="{% static 'accounts/js/main/bootstrap.min.js' %}"></script>
  </body>
</html>

Asterix/templates/home_2.html
{% extends "base.html" %}

{% block content %}

<h1>{{ title }}</h1>


{% for a in blog_list %}
    {% include 'blog/list-inline.html' with blog_post=a truncate=True detail=False %}
{% endfor %}


    
{% endblock %}

Asterix/templates/js.html
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

Asterix/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Axsterix</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/blog">Blog</a>
      </li>
      
    </ul>
    <form class="form-inline my-2 my-lg-0" action='/search/'>
      <input class="form-control mr-sm-2" type="search" name='q' placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

Asterix/templates/navbar_search.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Asterix</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/blog">Blog</a>
      </li>
      
    </ul>
  </div>
</nav>

Asterix/templates/scr_base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block head_title %}{% endblock %} CFE</title>
  </head>
  <body>
    {% include 'navbar_search.html' %}
    <div class='container-fluid'>
         {% block content %}
            {% endblock %}
    </div>

    {% include 'js.html' %}
  </body>
</html>

Asterix/templates/srh_base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block head_title %}{% endblock %} CFE</title>
  </head>
  <body>
    {% include 'navbar_search.html' %}
    <div class='container-fluid'>
         {% block content %}
            {% endblock %}
    </div>

    {% include 'js.html' %}
  </body>
</html>